# Generated by Django 5.0.6 on 2024-06-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='supplier',
            new_name='suppliers',
        ),
    ]
