# Generated by Django 5.0.6 on 2024-06-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_supplier_item_suppliers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='suppliers',
        ),
        migrations.AddField(
            model_name='supplier',
            name='items',
            field=models.ManyToManyField(related_name='suppliers', to='inventory.item'),
        ),
    ]
